api/urls.py
from django.urls import path
from .views import SearchBook, SearchViewfunc, Signup, UserLogin, UserLogout, paginated_view, BookListView, UserCreateDone, UserCreateComplete, PasswordReset, PasswordResetDone, PasswordResetConfirm, PasswordResetComplete, UserSetting, export_file, updatebook
app_name = "api"

urlpatterns = [
    path('', SearchViewfunc, name='top'),
    path('search/', SearchBook.as_view(), name='search'), # ここは検索結果をsesionに保存だけしてsearch/result/へリダイレクトさせる
    path('search/result/', paginated_view, name='search-result'), # ページネーションつきのページを表示する
    path('signup/', Signup.as_view(), name='signup'),
    path('login/', UserLogin.as_view(), name='login'),
    path('logout/', UserLogout.as_view(), name='logout'),
    path('mypage/', BookListView.as_view(), name='mypage'),
    path('signup/signup_done', UserCreateDone.as_view(), name='signup_done'),
    path('signup/signup_complete/<token>/', UserCreateComplete.as_view(), name='user_create_complete'),
    path('password_reset/', PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('setting/', UserSetting.as_view(), name='setting'), #マイページの各種設定変更画面へ
    path('mypage/export/', export_file, name='export'),
    path('mypage/update_bookpage/<int:pk>/', updatebook, name='update_bookpage'),
]

djangobook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# division_by_zero = 1 / 0

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('api.urls')),
    # path('sentry-debug/', division_by_zero),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # settings.pyファイルのMEDIA_URLで指定してあるURLが入力されると、同じくsettings.pyファイルのMEDIA_ROOTで指定されているフォルダから画像を呼び出してくる。

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    <header>
        <!-- ヘッダー全体 -->
        <div class="items-center justify-between">
            <!-- ヘッダーの左側 -->
            <div class="flex items-center">
                <span>文献一覧作成ツール</span>
            </div>
            <!-- ヘッダーの右側 -->
            <div>
                <nav class="space-x-4">
                  <form method="post" action="{% url "api:logout" %}">
                    {% csrf_token %}
                    <button type="submit">Logout</button>
                  </form>

                </nav>
            </div>
        </div>
    </header>

    {% block content %}
    {% endblock content %}

</body>
</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <script src="https://cdn.tailwindcss.com"></script>

</head>
<body class="h-full">
    <header class="border-b border-gray-100 shadow-md relative z-10">
        <!-- ヘッダー全体 -->
        <div class="flex justify-between py-4 px-10">
            <!-- ヘッダーの左側 -->
            <div class="flex items-center">
                <a href="{% url "api:top" %}">
                    <span class="text-2xl font-semibold tracking-tight
                    bg-gradient-to-r from-slate-800 via-gray-700 to-neutral-700
                    bg-clip-text text-transparent">文献一覧作成ツール</span>
                </a>
            </div>
        </div>
    </header>
    <div class="bg-cover bg-center bg-white flex flex-col h-full ">
        <div class="flex flex-col items-center pt-10">
            <div class="w-4/5">
                <div id="title" class="pb-2">
                    <span class="text-2xl font-bold">Login</span>
                </div>
            </div>
            <div id="content" class="flex items-center justify-center bg-gray-200 mx-10 mb-10 py-20 w-4/5 h-3/5 shadow-md">
                <div class="flex items-center justify-center w-11/12 h-5/6 space-x-16">
                    <div class="w-full ml-10">
                        <form method="post" action="/login/" class="space-y-6 px-16">{% csrf_token %}
                            <!-- usernameタグ -->
                            <!-- <div class="">
                                <label htmlFor="email" class="block text-sm font-medium leading-6">
                                    ユーザー名
                                </label>
                                <div class="mt-2"> -->
                                    <!-- ここにdjangoのforms.pyから受け取るusernameのログインフォームを書く -->
                                    <!-- {{ form.username }} -->
                                    <!-- <input name="username" type="text" required autoComplete="username" placeholder="ユーザー名を入力してください" class="block w-full border-0 px-2 py-1.5 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset sm:text-sm sm:leading-6" required/> -->
                                <!-- </div>
                            </div> -->

                            <!-- passwordタグ -->
                            <!-- <div class="">
                                <div class="flex items-center justify-between">
                                    <label htmlFor="password" class="block text-sm font-medium leading-6">
                                        パスワード
                                    </label> -->
                                <!-- </div>
                                <div class="mt-2"> -->
                                <!-- ここにdjangoのforms.pyから受け取るpasswordのログインフォームを書く -->
                                    <!-- {{ form.password }} -->
                                    <!-- <input name="password" type="password" required autoComplete="current-password" placeholder="パスワードを入力してください" class="block w-full border-0 px-2 py-1.5 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset sm:text-sm sm:leading-6"/> -->
                                <!-- </div>
                            </div> -->

                            <!-- 認証エラーメッセージの表示 -->
                            <!-- {% for error in form.non_field_errors %}
                            <div class="alert alert-danger" role="alert">
                            <p>{{ error }}</p>
                            </div>
                            {% endfor %} -->

                            {% for field in form %}
                                <div>
                                    <label htmlFor="email" class="block text-sm font-medium leading-6">
                                        {{ field.label_tag }}
                                    </label>
                                    <div class="mt-2">
                                        {{ field }}
                                    </div>
                                    {{ field.errors }}
                                </div>
                            {% endfor %}
                            {{ form.non_field_errors }}

                            <div class="flex justify-center pt-5">
                                <button type="submit" class="flex justify-center w-full py-2 mb-5 tracking-widest bg-black text-sm text-white font-semibold leading-6 shadow-sm hover:bg-white hover:text-black hover:duration-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600">
                                    ログイン
                                </button>
                            </div>
                        </form>
                        <div class="pb-4 text-center">
                            <a href="{% url 'api:password_reset' %}">パスワードを忘れた方はクリック</a>
                        </div>
                    </div>
                    <div class="w-full border-l border-dotted border-black">
                        <div class="mr-10 py-10 space-y-6 text-center">
                            <span class="text-lg font-semibold">はじめてご利用の方</span>
                            <p class="">検索資料を保存したい方はアカウント作成が必要です</p>
                            <div class="px-12">
                                <a href="{% url 'api:signup' %}" class="flex justify-center w-full py-2 mb-5 tracking-widest bg-black text-sm text-white font-semibold leading-6 shadow-sm hover:bg-white hover:text-black hover:duration-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-600" >
                                    アカウント作成
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

templates/mypage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://cdn.tailwindcss.com"></script>

</head>
<body class="h-full">
    {% block content %}
    <header class="mb-3 border-b border-gray-100 shadow-md">
        <!-- ヘッダー全体 -->
        <div class="flex justify-between py-5 mx-10 border-gray-600">
            <!-- ヘッダーの左側 -->
            <div class="flex space-x-5">
                <div class="flex items-center">
                    <a href="{% url "api:top" %}">
                        <span class="text-2xl font-semibold tracking-tight
                        bg-gradient-to-r from-slate-800 via-gray-700 to-neutral-700
                        bg-clip-text text-transparent">文献一覧作成ツール</span>
                    </a>
                </div>
                <!-- <a href="{% url "api:top" %}" class="text-xl font-bold">Search</a> -->
                <div class="flex items-center">
                    <form action="/search/" method="post">
                        <div class="relative w-96">
                            <!-- <input type="text" class="w-full block border mr-6 px-3 py-1 rounded-full bg-gray-100 border-gray-600" id="searchword" name="searchword" value="{{ search_word }}"/> -->
                            {{ form.searchword }}
                            {{ form.searchword.errors }}
                            {% csrf_token %}
                            <button type="submit" class="absolute right-2 top-2/4 -translate-y-2/4">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z" />
                                    </svg>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
            <!-- ヘッダーの右側 -->
            <div class="flex items-center">
                <nav class="space-x-4">
                    <form method="post" action="{% url "api:logout" %}">
                        {% csrf_token %}
                        <button type="submit" class="font-semibold">Logout</button>
                    </form>
                </nav>
            </div>
        </div>
    </header>
    <main>
        <div class="flex justify-center">
            <div class="flex items-center justify-end w-4/5">
                <form method="post" action="{% url "api:export" %}">{% csrf_token %}
                    <select name="output" class="border border-gray-600 rounded-md">
                        <option value="csv">CSV</option>
                        <option value="text">TEXT</option>
                    </select>
                    <button type="submit" class="px-3 text-center bg-black rounded-md shadow-md text-white hover:bg-gray-300 hover:text-black hover:duration-500" >出力</button>
                </form>
            </div>
        </div>
        <div class="">
            {% for book in book_obj %}
                <form method="post" action="">{% csrf_token %}
                    <div class=" pt-3 pb-5 border-b-2 border-dotted border-gray-600" value="{{ book }}">
                        <div class="px-4">
                            <a href="{% url 'api:update_bookpage' book.pk %}"><p name="title" class="font-bold py-2 text-xl">タイトル: {{ book.title }}</p></a>
                            <input name="title" type="hidden" value="{{ book.title }}">
                            {% for author in book.author.all %}
                                <div><p name="author">著者・編者: {{ author.author }}</p></div>
                            <!-- <input name="author" type="hidden" value="{{ book.author }}"> -->
                            {% endfor %}
                            {% for type in book.type.all %}
                                <div><p name="type">資料種別: {{ type.type }}</p></div>
                            {% endfor %}
                            <!-- <input name="type" type="hidden" value="{{ book.type }}"> -->
                            <div><p name="publisher">出版社: {{ book.publisher.publisher }}</p></div>
                            <input name="publisher" type="hidden" value="{{ book.publisher }}">
                            {% if book.type == "記事" %}
                                {% for magazine_title in book.magazine_title.all %}
                                    <div><p name="magazine_title">掲載誌: {{ magazine_title.magazine_title }}</p></div>
                                {% endfor %}
                                <!-- <input name="magazine_title" type="hidden" value="{{ book.magazine_title }}"> -->
                                <div><p name="page">掲載ページ: {{ book.page }}</p></div>
                                <input name="page" type="hidden" value="{{ book.page }}">
                            {% endif %}
                            <div><p name="date">出版年: {{ book.date }}</p></div>
                            <input name="date" type="hidden" value="{{ book.date }}">
                            <div>リンク: <a name="link" href="{{ book.link }}">{{ book.link }}</a></div>
                            <input name="link" type="hidden" value="{{ book.link }}">
                        </div>
                    </div>
                </form>
            {% endfor %}
        </div>
        <!-- ページネーションのページ表示 -->
        <div class="pagination mt-8 mb-4 flex justify-center">
            <ul class="pagination flex space-x-2">
                <!-- 前のページ -->
                {% if page_obj.has_previous %}
                    <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link text-primary d-inline-block">前</a></li>
                {% else %}
                    <li class="disabled"><div class="page-link text-secondary d-inline-block disabled" href="#">前</div></li>
                {% endif %}
                <!-- ページ番号 -->
                {% for num in page_obj.paginator.page_range %}
                    {% if num %}
                        {% if num == page_obj.number %}
                            <li class="current-page">
                                <div class="bg-black text-white rounded px-2">
                                    {{ num }}
                                </div>
                            </li>
                        <!-- 前後3ページ以内をページ番号に表示 -->
                        {% elif page_obj.number|add:"4" >= num and page_obj.number|add:"-4" <= num %}
                            <li>
                                <a href="?page={{ num }}" class="page-link text-primary d-inline-block rounded px-2">
                                    {{ num }}
                                </a>
                            </li>
                        {% endif %}
                    {% endif %}
                {% endfor %}
                <!-- 次のページ -->
                {% if page_obj.has_next %}
                    <li>
                        <a href="?page={{ page_obj.next_page_number }}" class="page-link text-primary d-inline-block">
                            次
                        </a>
                    </li>
                {% else %}
                    <li class="disabled">
                        <div class="page-link text-secondary d-inline-block disabled">
                            次
                        </div>
                    </li>
                {% endif %}
                <!-- 現在のページと総ページ数 -->
                <li class="pl-3 p-md-2 text-gray-600">
                    {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
                </li>
            </ul>
        </div>
        {% endblock content %}
    </main>
</body>
</html>

templates/password_reset_complete.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>パスワードリセット完了</title>
    <script src="https://cdn.tailwindcss.com"></script>

</head>
<body class="h-screen flex flex-col">
    <header class="border-b border-gray-100 shadow-md">
        <!-- ヘッダー全体 -->
        <div class="flex justify-between py-4 px-10 shadow-md bg-white">
            <!-- ヘッダーの左側 -->
            <div class="flex items-center">
                <a href="{% url "api:top" %}">
                    <span class="text-2xl font-semibold tracking-tight
                    bg-gradient-to-r from-slate-800 via-gray-700 to-neutral-700
                    bg-clip-text text-transparent">文献一覧作成ツール</span>
                </a>
            </div>
        </div>
    </header>
    <main class="flex-grow flex items-center justify-center">
        <div class="flex justify-center justify-start h-2/5 w-2/5">
            <div class="flex flex-col items-center w-full">
                <p class="text-2xl font-bold tracking-widest">
                    パスワードの再設定が完了しました
                </p>
                <div class="flex w-full">
                    <div class="w-full flex items-center justify-center mx-8 mt-8 py-2 rounded-full font-semibold tracking-widest bg-black text-white border border-black hover:text-black hover:bg-white duration-500">
                        <p><a href="{% url 'api:top' %}">検索画面へ</a></p>
                    </div>
                    <div class="w-full flex items-center justify-center mx-8 mt-8 py-2 rounded-full font-semibold tracking-widest bg-black text-white border border-black hover:text-black hover:bg-white duration-500">
                        <p><a href="{% url 'api:login' %}">ログイン画面へ</a></p>
                    </div>
                </div>
            </div>
        </div>
    </main>
</body>
</html>

templates/result.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mypage</title>
    <script src="https://cdn.tailwindcss.com"></script>

</head>
<body class="h-full">
    {% block content %}
    <header class="mb-3 border-b border-gray-100 shadow-md">
        <!-- ヘッダー全体 -->
        <div class="flex justify-between py-5 mx-10 border-gray-600">
            <!-- ヘッダーの左側 -->
            <div class="flex space-x-5">
                <div class="flex items-center">
                    <a href="{% url "api:top" %}">
                        <span class="text-2xl font-semibold tracking-tight
                        bg-gradient-to-r from-slate-800 via-gray-700 to-neutral-700
                        bg-clip-text text-transparent">文献一覧作成ツール</span>
                    </a>
                </div>
                <!-- <a href="{% url "api:top" %}" class="text-xl font-bold">Search</a> -->
                <div class="flex items-center">
                    <form action="/search/" method="post">
                        <div class="relative w-96">
                            <!-- <input type="text" class="w-full block border mr-6 px-3 py-1 rounded-full bg-gray-100 border-gray-600" id="searchword" name="searchword" value="{{ search_word }}"/> -->
                            {{ form.searchword }}
                            {{ form.searchword.errors }}
                            {% csrf_token %}
                            <button type="submit" class="absolute right-2 top-2/4 -translate-y-2/4">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z" />
                                    </svg>
                            </button>
                        </div>

                    </form>
                </div>
            </div>
            <!-- ヘッダーの右側 -->
            {% if user.is_authenticated %}
            <div class="flex items-center">
                <nav class="flex justify-center space-x-4">
                    <a href="{% url 'api:mypage' %}"><button type="submit" class="font-semibold">Mypage</button></a>
                    <form method="post" action="{% url "api:logout" %}">
                        {% csrf_token %}
                        <button type="submit" class="font-semibold">Logout</button>
                    </form>
                </nav>
            </div>
            {% else %}
            <div class="flex items-center">
                <nav class="flex justify-center justify-between space-x-5">
                    <form method="post" action="{% url "api:login" %}">
                        {% csrf_token %}
                        <button type="submit" class="font-semibold">Login</button>
                    </form>
                    <form method="post" action="{% url "api:signup" %}">
                        {% csrf_token %}
                        <button type="submit" class="font-semibold">Signup</button>
                    </form>

                </nav>
            </div>
            {% endif %}
        </div>
    </header>
    <main>
        <div class="">
            {% for book in page_obj %}
                <form method="post" action="">{% csrf_token %}
                    <div class=" pt-2 pb-6 border-b-2 border-dotted border-gray-600" value="{{ book }}">
                        <div class="px-4">
                            <p name="title" class="font-bold py-2 text-xl">タイトル: {{ book.title }}</p>
                            <input name="title" type="hidden" value="{{ book.title }}">
                            <div><p name="author">著者・編者: {{ book.author }}</p></div>
                            <input name="author" type="hidden" value="{{ book.author }}">
                            <div><p name="category">資料種別: {{ book.category }}</p></div>
                            <input name="category" type="hidden" value="{{ book.category }}">
                            <div><p name="publisher">出版社: {{ book.publisher }}</p></div>
                            <input name="publisher" type="hidden" value="{{ book.publisher }}">
                            {% if book.category == "記事" %}
                            <div><p name="thesis">掲載誌: {{ book.thesis }}</p></div>
                            <input name="thesis" type="hidden" value="{{ book.thesis }}">
                            <div><p name="page">掲載ページ: {{ book.page }}</p></div>
                            <input name="page" type="hidden" value="{{ book.page }}">
                            {% endif %}
                            <div><p name="publish_year">出版年: {{ book.publish_year }}</p></div>
                            <input name="publish_year" type="hidden" value="{{ book.publish_year }}">
                            <div>リンク: <a name="link" href="{{ book.link }}">{{ book.link }}</a></div>
                            <input name="link" type="hidden" value="{{ book.link }}">
                            {% if user.is_authenticated %}
                            <div class="mt-2">
                                <button type="submit" class="h-9 text-center bg-black rounded-full shadow-md w-32 text-white hover:bg-gray-300 hover:text-black hover:duration-500">
                                    お気に入り
                                </button>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </form>
            {% endfor %}
        </div>
        <!-- ページネーションのページ表示 -->
        <div class="pagination mt-8 mb-4 flex justify-center">
            <ul class="pagination flex space-x-2">
                <!-- 前のページ -->
                {% if page_obj.has_previous %}
                    <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link text-primary d-inline-block">前</a></li>
                {% else %}
                    <li class="disabled"><div class="page-link text-secondary d-inline-block disabled" href="#">前</div></li>
                {% endif %}
                <!-- ページ番号 -->
                {% for num in page_obj.paginator.page_range %}
                    {% if num %}
                        {% if num == page_obj.number %}
                            <li class="current-page">
                                <div class="bg-black text-white rounded px-2">
                                    {{ num }}
                                </div>
                            </li>
                        <!-- 前後3ページ以内をページ番号に表示 -->
                        {% elif page_obj.number|add:"4" >= num and page_obj.number|add:"-4" <= num %}
                            <li>
                                <a href="?page={{ num }}" class="page-link text-primary d-inline-block rounded px-2">
                                    {{ num }}
                                </a>
                            </li>
                        {% endif %}
                    {% endif %}
                {% endfor %}
                <!-- 次のページ -->
                {% if page_obj.has_next %}
                    <li>
                        <a href="?page={{ page_obj.next_page_number }}" class="page-link text-primary d-inline-block">
                            次
                        </a>
                    </li>
                {% else %}
                    <li class="disabled">
                        <div class="page-link text-secondary d-inline-block disabled">
                            次
                        </div>
                    </li>
                {% endif %}
                <!-- 現在のページと総ページ数 -->
                <li class="pl-3 p-md-2 text-gray-600">
                    {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
                </li>
            </ul>
        </div>
    {% endblock content %}
    </main>
</body>
</html>

templates/search.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Search</title>
<script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="h-full">
    <header class="border-b border-gray-100 shadow-md">
        <!-- ヘッダー全体 -->
        <div class="flex justify-between mt-4 mx-10 pb-4">
            <!-- ヘッダーの左側 -->
            <div class="flex items-center">
                    <span class="text-2xl font-semibold tracking-tight
                    bg-gradient-to-r from-slate-800 via-gray-700 to-neutral-700
                    bg-clip-text text-transparent">文献一覧作成ツール</span>
            </div>
            <!-- ヘッダーの右側 -->
            {% if user.is_authenticated %}
            <div class="flex items-center">
                <nav class="flex justify-center space-x-4">
                    <a href="{% url 'api:mypage' %}"><button type="submit" class="font-semibold">Mypage</button></a>
                    <form method="post" action="{% url "api:logout" %}">
                        {% csrf_token %}
                        <button type="submit" class="font-semibold">Logout</button>
                    </form>

                </nav>
            </div>
            {% else %}
            <div>
                <nav class="flex justify-between space-x-5">
                    <form method="post" action="{% url "api:login" %}">
                        {% csrf_token %}
                        <button type="submit" class="font-semibold">Login</button>
                    </form>
                    <form method="post" action="{% url "api:signup" %}">
                        {% csrf_token %}
                        <button type="submit" class="font-semibold">Signup</button>
                    </form>

                </nav>
            </div>
            {% endif %}
        </div>
    </header>
    <main class="">
        <div class="flex flex-col items-center mt-48">
            <div class="w-full flex justify-center px-5 pb-5">
                <form action="/search/" class="w-full flex flex-col items-center space-y-4" method="post">
                  {% csrf_token %}
                    <div class="w-7/12">
                        {% if messages %}
                            {% for message in messages %}
                            <p class="text-blue-600">{{ message }}</p>
                            {% endfor %}
                        {% endif %}
                        {{ form.non_field_errors }}
                        <div class="pb-2">
                            <label class="text-xl font-semibold" for="{{ form.searchword.id_for_label }}">検索ワード</label>
                        </div>
                        <div class="w-full flex justify-center text-center">
<!-- {#                            <input type="text"#}
{#                                    class="block w-full h-12 pl-5 border rounded-full bg-gray-100 border-gray-600 shadow-md"#}
{#                                    id="searchword" placeholder="書籍名、論文名、著者名等を入力してください" name="searchword"#}
{#                                    value="{{ search_word }}"/>#} -->
                              {{ form.searchword }}
                              {{ form.searchword.errors }}
                        </div>
                    </div>
                    <div class="w-1/5">
                        <button
                            class="h-9 text-center w-full bg-black rounded-full shadow-md text-white hover:bg-gray-300 hover:text-black hover:duration-500"
                            type="submit" value="search">検索する
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </main>
</body>

templates/user_create_complete.html
{% block content %}
<p>
    本登録が完了しました。<br>
    登録されたメールアドレスとパスワードでログインしてください。<br>
    <a class="btn btn-primary btn-lg" href="{% url 'api:login' %}">ログイン</a>
</p>
{% endblock %}